/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import com.db4o.Db4oEmbedded;
import com.db4o.ObjectContainer;
import controllers.ContainerController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.GroupLayout.SequentialGroup;
import javax.swing.JCheckBox;
import javax.swing.JPanel;
import models.Container;

/**
 *
 * @author fauzan-radji
 */
public class MainFrame extends javax.swing.JFrame {

  ObjectContainer db;
  ContainerController containerController;
  List<Container> containers;

  /**
   * Creates new form MainFrame
   */
  public MainFrame() {
    // init db
    initDB("db.yap");
    containerController = new ContainerController(db);
    containers = containerController.getAll();

    initComponents();
  }

  public void initDB(String dbName) {
    db = Db4oEmbedded.openFile(Db4oEmbedded.newConfiguration(), dbName);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    buttonTambah = new javax.swing.JButton();
    layeredPane = new javax.swing.JLayeredPane();
    List<JPanel> panels = new ArrayList<>();
    for (Container container : containers) {
      panels.add(instantiatePanel(container));
    }

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    buttonTambah.setText("Tambah");

    layeredPane.setBorder(
      javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))
    );

    for (JPanel panel : panels) {
      setupPanelTodo(panel);
    }

    javax.swing.GroupLayout layeredPaneLayout = new javax.swing.GroupLayout(
      layeredPane
    );
    layeredPane.setLayout(layeredPaneLayout);

    SequentialGroup sequentialGroup = layeredPaneLayout.createSequentialGroup();
    for (JPanel panel : panels) {
      sequentialGroup
        .addComponent(
          panel,
          javax.swing.GroupLayout.PREFERRED_SIZE,
          javax.swing.GroupLayout.DEFAULT_SIZE,
          javax.swing.GroupLayout.PREFERRED_SIZE
        )
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED);
    }

    layeredPaneLayout.setHorizontalGroup(
      layeredPaneLayout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layeredPaneLayout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              layeredPaneLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(sequentialGroup)
            )
            .addContainerGap(
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
        )
    );
    layeredPaneLayout.setVerticalGroup(
      layeredPaneLayout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layeredPaneLayout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              layeredPaneLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(
                  panels.get(0),
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(
                  panels.get(1),
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(
                  panels.get(2),
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(
                  panels.get(3),
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addContainerGap(
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
        )
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
      getContentPane()
    );
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(buttonTambah)
                )
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(layeredPane)
                )
            )
            .addContainerGap()
        )
    );
    layout.setVerticalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addContainerGap()
            .addComponent(buttonTambah)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(layeredPane)
            .addContainerGap()
        )
    );

    pack();
  } // </editor-fold>//GEN-END:initComponents

  public JPanel instantiatePanel(Container container) {
    JPanel panelTodo = new javax.swing.JPanel();

    return panelTodo;
  }

  public void setupPanelTodo(JPanel panel) {
    panel.setBorder(
      javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))
    );

    JCheckBox jCheckBox00 = new javax.swing.JCheckBox();
    JCheckBox jCheckBox01 = new javax.swing.JCheckBox();
    JCheckBox jCheckBox02 = new javax.swing.JCheckBox();
    JCheckBox jCheckBox03 = new javax.swing.JCheckBox();

    jCheckBox00.setText("Task 1");
    jCheckBox01.setText("Task 2");
    jCheckBox02.setText("Task 3");
    jCheckBox03.setText("Task 4");

    javax.swing.GroupLayout panelTodo0Layout = new javax.swing.GroupLayout(
      panel
    );
    panel.setLayout(panelTodo0Layout);
    panelTodo0Layout.setHorizontalGroup(
      panelTodo0Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          panelTodo0Layout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              panelTodo0Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(
                  jCheckBox00,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  110,
                  Short.MAX_VALUE
                )
                .addComponent(
                  jCheckBox01,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
                .addComponent(
                  jCheckBox02,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
                .addComponent(
                  jCheckBox03,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
            )
            .addGap(50, 50, 50)
        )
    );
    panelTodo0Layout.setVerticalGroup(
      panelTodo0Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          panelTodo0Layout
            .createSequentialGroup()
            .addContainerGap()
            .addComponent(jCheckBox00)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jCheckBox01)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jCheckBox02)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jCheckBox03)
            .addContainerGap(
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
        )
    );
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger
        .getLogger(MainFrame.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger
        .getLogger(MainFrame.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger
        .getLogger(MainFrame.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger
        .getLogger(MainFrame.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(
      new Runnable() {
        public void run() {
          new MainFrame().setVisible(true);
        }
      }
    );
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton buttonTambah;
  private javax.swing.JLayeredPane layeredPane;
  // End of variables declaration//GEN-END:variables
}
