/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import com.db4o.Db4oEmbedded;
import com.db4o.ObjectContainer;
import controllers.ContainerController;
import controllers.TodoController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.ParallelGroup;
import javax.swing.GroupLayout.SequentialGroup;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import models.Container;
import models.Todo;

/**
 *
 * @author fauzan-radji
 */
public class MainFrame extends javax.swing.JFrame {

  ObjectContainer db;
  ContainerController containerController;
  TodoController todoController;
  List<Container> containers;
  AddTodoInternalFrame addTodoInternalFrame;

  /**
   * Creates new form MainFrame
   */
  public MainFrame() {
    // init db
    initDB("db.yap");
    containerController = new ContainerController(db);
    todoController = new TodoController(db);
    containers = containerController.getAll();

    addTodoInternalFrame = new AddTodoInternalFrame(db, containerController);
    addTodoInternalFrame.setClosable(true);
    add(addTodoInternalFrame);

    initComponents();
  }

  public void initDB(String dbName) {
    db = Db4oEmbedded.openFile(Db4oEmbedded.newConfiguration(), dbName);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    buttonTambah = new javax.swing.JButton();
    layeredPane = new javax.swing.JLayeredPane();
    jPanel = new JPanel();
    List<JPanel> panels = new ArrayList<>();
    for (Container container : containers) {
      JPanel panel = instantiatePanel(container);

      List<Todo> todos = todoController.getByContainerId(container.getId());
      setupPanelTodo(panel, todos);
      panel.addMouseListener(
        new java.awt.event.MouseAdapter() {
          public void mouseClicked(java.awt.event.MouseEvent evt) {
            panelTodoMouseClicked(evt, container, db);
          }
        }
      );

      panels.add(panel);
    }

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    buttonTambah.setText("Tambah");
    buttonTambah.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          buttonTambahActionPerformed(evt);
        }
      }
    );

    jPanel.setBorder(
      javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))
    );

    GroupLayout jPanelLayout = new GroupLayout(jPanel);
    jPanel.setLayout(jPanelLayout);

    SequentialGroup sequentialGroup = jPanelLayout.createSequentialGroup();
    for (JPanel panel : panels) {
      sequentialGroup
        .addComponent(
          panel,
          GroupLayout.PREFERRED_SIZE,
          GroupLayout.DEFAULT_SIZE,
          GroupLayout.PREFERRED_SIZE
        )
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED);
    }

    jPanelLayout.setHorizontalGroup(
      jPanelLayout
        .createParallelGroup(GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanelLayout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              jPanelLayout
                .createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(sequentialGroup)
            )
            .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        )
    );

    ParallelGroup parallelGroup = jPanelLayout.createParallelGroup(
      GroupLayout.Alignment.LEADING
    );
    for (JPanel panel : panels) {
      parallelGroup.addComponent(
        panel,
        GroupLayout.PREFERRED_SIZE,
        GroupLayout.DEFAULT_SIZE,
        GroupLayout.PREFERRED_SIZE
      );
    }

    jPanelLayout.setVerticalGroup(
      jPanelLayout
        .createParallelGroup(GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanelLayout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(parallelGroup)
            .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        )
    );

    layeredPane.setLayer(jPanel, JLayeredPane.DEFAULT_LAYER);
    layeredPane.setLayer(addTodoInternalFrame, JLayeredPane.MODAL_LAYER);

    GroupLayout layout = new GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addGroup(
              layout
                .createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(buttonTambah)
                )
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel)
                )
            )
            .addContainerGap()
        )
    );
    layout.setVerticalGroup(
      layout
        .createParallelGroup(GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addContainerGap()
            .addComponent(buttonTambah)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel)
            .addContainerGap()
        )
    );

    pack();
  } // </editor-fold>//GEN-END:initComponents

  public JPanel instantiatePanel(Container container) {
    JPanel panelTodo = new javax.swing.JPanel();

    return panelTodo;
  }

  public void setupPanelTodo(JPanel panel, List<Todo> todos) {
    panel.setBorder(
      javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))
    );

    List<JCheckBox> checkBoxes = new ArrayList<>();
    JLabel emptyLabel = new JLabel("Belum ada tugas");
    if (todos != null) {
      for (Todo todo : todos) {
        JCheckBox checkBox = new javax.swing.JCheckBox();
        checkBoxes.add(checkBox);
        checkBox.setText(todo.getTask());
      }
    }

    GroupLayout panelLayout = new GroupLayout(panel);
    panel.setLayout(panelLayout);
    ParallelGroup parallelGroup = panelLayout.createParallelGroup(
      GroupLayout.Alignment.LEADING
    );
    if (checkBoxes.isEmpty()) {
      parallelGroup.addComponent(
        emptyLabel,
        GroupLayout.DEFAULT_SIZE,
        GroupLayout.DEFAULT_SIZE,
        Short.MAX_VALUE
      );
    } else {
      for (JCheckBox checkBox : checkBoxes) {
        parallelGroup.addComponent(
          checkBox,
          GroupLayout.DEFAULT_SIZE,
          GroupLayout.DEFAULT_SIZE,
          // 110,
          Short.MAX_VALUE
        );
      }
    }
    panelLayout.setHorizontalGroup(
      panelLayout
        .createParallelGroup(GroupLayout.Alignment.LEADING)
        .addGroup(
          panelLayout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(parallelGroup)
            .addGap(50, 50, 50)
        )
    );
    SequentialGroup sequentialGroup = panelLayout.createSequentialGroup();
    sequentialGroup.addContainerGap();
    if (checkBoxes.isEmpty()) {
      sequentialGroup.addComponent(emptyLabel);
    } else {
      for (JCheckBox checkBox : checkBoxes) {
        sequentialGroup
          .addComponent(checkBox)
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED);
      }
    }

    panelLayout.setVerticalGroup(
      panelLayout
        .createParallelGroup(GroupLayout.Alignment.LEADING)
        .addGroup(
          sequentialGroup.addContainerGap(
            GroupLayout.DEFAULT_SIZE,
            Short.MAX_VALUE
          )
        )
    );
  }

  private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
    addTodoInternalFrame.setVisible(true);
  }

  private void panelTodoMouseClicked(
    java.awt.event.MouseEvent evt,
    Container container,
    ObjectContainer db
  ) {
    // TODO add your handling code here:
    ListFrame listFrame = new ListFrame(container, db);
    listFrame.setVisible(true);
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger
        .getLogger(MainFrame.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger
        .getLogger(MainFrame.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger
        .getLogger(MainFrame.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger
        .getLogger(MainFrame.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(
      new Runnable() {
        public void run() {
          new MainFrame().setVisible(true);
        }
      }
    );
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton buttonTambah;
  private javax.swing.JLayeredPane layeredPane;
  private javax.swing.JPanel jPanel;
  // End of variables declaration//GEN-END:variables
}
